networks:
  log-api:

services:
  nginx:
    image: nginx:stable
    container_name: nginx_log_api
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www:delegated
      - ./docker-dev/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - log-api
  mysql:
    image: mysql:lts
    container_name: mysql_log_api
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - meeting-room-app
    volumes:
      - mysql_data:/var/lib/mysql:rw
  app:
    build:
      context: ./
      dockerfile: docker-dev/Dockerfile
    container_name: we_log_api
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./vendor:/var/www/vendor:cached
    networks:
      - log-api
volumes:
  mysql_data: